import type JSZip from "jszip"
import type { Project, ProjectMember } from "./modrinth"
import TOML from "@ltd/j-toml"
import { ALL_GAME_VERSIONS } from "./constants"

export async function packageDatapack({
  zip,
  project,
  members,
  versionNumber,
  gameVersions,
  loaders,
}: {
  zip: JSZip
  project: Project
  members: ProjectMember[]
  versionNumber: string
  gameVersions: string[]
  loaders: ("fabric" | "quilt" | "forge" | "neoforge")[]
}) {
  const newVersionNumber = /^\d/.test(versionNumber) ? versionNumber : `1-${versionNumber}`
  const newSlug = project.slug.replace("-", "_").replace(/\W/g, "").substring(0, 63)
  const iconPath = `${project.slug}_pack.png`

  const fabricModJson = {
    schemaVersion: 1,
    id: newSlug,
    version: newVersionNumber,
    name: project.title,
    description: project.description,
    authors: members.map((member) => member.user.username),
    contact: {
      homepage: `https://modrinth.com/${project.project_type}/${project.slug}`,
      sources: "https://github.com/TheLokin/mc-packs",
      issues: "https://github.com/TheLokin/mc-packs/issues",
    },
    license: project.license.id,
    icon: iconPath,
    environment: "*",
    depends: {
      "fabric-resource-loader-v0": "*",
    },
  }

  const quiltModJson = {
    schema_version: 1,
    quilt_loader: {
      group: "dev.thelokin",
      id: newSlug,
      version: newVersionNumber,
      metadata: {
        name: project.title,
        description: project.description,
        contributors: members.reduce(
          (acc, member) => ({
            ...acc,
            [member.user.username]: member.role,
          }),
          {},
        ),
        contact: {
          homepage: `https://modrinth.com/${project.project_type}/${project.slug}`,
          sources: "https://github.com/TheLokin/mc-packs",
          issues: "https://github.com/TheLokin/mc-packs/issues",
        },
        icon: iconPath,
      },
      intermediate_mappings: "net.fabricmc:intermediary",
      depends: [
        {
          id: "quilt_resource_loader",
          versions: "*",
          unless: "fabric-resource-loader-v0",
        },
      ],
    },
  }

  const cutoffIndex = ALL_GAME_VERSIONS.indexOf("1.18.2")

  let maximumIndex = Number.MIN_VALUE
  for (const gameVersion of gameVersions) {
    const index = ALL_GAME_VERSIONS.indexOf(gameVersion)
    if (index > maximumIndex) {
      maximumIndex = index
    }
  }

  const newForge = maximumIndex < cutoffIndex

  const forgeModsToml = {
    modLoader: newForge ? "lowcodefml" : "javafml",
    loaderVersion: newForge ? "[40,)" : "[25,)",
    license: project.license.id,
    showAsResourcePack: false,
    mods: [
      {
        modId: newSlug,
        version: newVersionNumber,
        displayName: project.title,
        description: project.description,
        logoFile: iconPath,
        updateJSONURL: `https://api.modrinth.com/updates/${project.id}/forge_updates.json`,
        credits: "Generated by TheLokin",
        authors: members.map((member) => member.user.username).join(", "),
        displayURL: `https://modrinth.com/${project.project_type}/${project.slug}`,
      },
    ],
    issueTrackerURL: "https://github.com/TheLokin/mc-packs/issues",
  }

  const neoModsToml = {
    ...forgeModsToml,
    modLoader: "javafml",
    loaderVersion: "[1,)",
    mods: forgeModsToml.mods.map((mod) => ({
      ...mod,
      updateJSONURL: `${mod.updateJSONURL}?neoforge=only`,
    })),
  }

  if (loaders.includes("fabric")) {
    zip.file("fabric.mod.json", JSON.stringify(fabricModJson, null, 2))
  }
  if (loaders.includes("quilt")) {
    zip.file("quilt.mod.json", JSON.stringify(quiltModJson, null, 2))
  }
  if (loaders.includes("forge")) {
    zip.file("META-INF/mods.toml", TOML.stringify(forgeModsToml, { newline: "\n" }))
  }
  if (loaders.includes("neoforge")) {
    zip.file("META-INF/neoforge.mods.toml", TOML.stringify(neoModsToml, { newline: "\n" }))
  }

  if (!newForge && loaders.includes("forge")) {
    const classFile = new Uint8Array(
      await (
        await fetch("https://cdn.modrinth.com/wrapper/ModrinthWrapperRestiched.class")
      ).arrayBuffer(),
    )

    let binary = ""
    for (let i = 0; i < classFile.byteLength; i++) {
      binary += String.fromCharCode(classFile[i])
    }

    let sanitizedId = project.id
    if (/^\d+/.test(project.id)) {
      sanitizedId = `_${sanitizedId}`
    }

    sanitizedId = sanitizedId.substring(0, 8)

    binary = binary
      .replace(
        `${String.fromCharCode(32)}needs1to1be1changed1modrinth1mod`,
        String.fromCharCode(newSlug.length) + newSlug,
      )
      .replace("/wrappera/", `/${sanitizedId}/`)

    const newArray = []
    for (let i = 0; i < binary.length; i++) {
      newArray.push(binary.charCodeAt(i))
    }

    zip.file(`com/modrinth/${sanitizedId}/ModrinthWrapper.class`, new Uint8Array(newArray))
  }

  const iconFile = zip.file("pack.png")
  if (iconFile) {
    zip.file(iconPath, await iconFile.async("uint8array"))
  }

  return zip
}
